(import text)
(import cli)
#Base for all lisp defined elements, 
#default working as a stacker
(defclass TMLElement ()
    (attributes (dict))
    (children (list))
    (state-changed true)
    (input null)

    (set-children (children)
        (setl :children this children)
    )
    (constructor (children)
        (setl :children this children)
    )
    (updated ()
        (if :state-changed this (return true))
        (any (map updated :children this))
    )
    (handle-input (input)
        (if (not (eq :input this null))
            (return (handle-input :input this input))
        )
        false
    )
    (set-focus ()
        false
    )
    (get-cursor-info ()
        (if (not (eq :input this null))
            (return (get-cursor-info :input this))
        )
        (cursor-info 0 0)
    )
    (prefered-dims (dimensions)
        (setl prefered-width (max (map _(width (prefered-dims _ dimensions)) :children this)))
        (if (eq (type prefered-width) null_t) (setl prefered-width (width dimensions)))
        (setl prefered-height (height dimensions))
        (if (> (len :children this) 0)
            (setl prefered-height (foldl (map _(height (prefered-dims _ dimensions)) :children this) plus))

        )
        (dims prefered-width prefered-height)
    )

    (write (view redraw)
        (setl :state-changed this false)
        (setl view-dims (dims view))
        (setl height-offset 0)
        (setl current-offset (+ (len :children this) (minus 0 1)))
        (while (>= current-offset 0)
            (setl child ;current-offset :children this)
            (setl dimensions (prefered-dims child view-dims))
            (setl dimensions (dims (cond (< (width dimensions) 0) 1 (width dimensions) )  (cond (< (height dimensions) 0) 1 (height dimensions))  ))
            (if (|| redraw (updated child))
                (write child (sub-view view height-offset 0) redraw)
            )
            (incr height-offset (height dimensions))
            #(print height-offset)
            (incr current-offset (minus 0 1))
        )
    )



    (update ()
        (setl :state-changed this true)
    )
)


(defclass Attribute ()
    (name "")
    (value null)
    (mandatory true)
    (is-parameter-value true)
)
(defclass Header ()
    (name "")
    (attributes (dict))
    (field-name null)
)

(defclass Element ()
    (header (Header))
    (children (list))
    (extra-fields (list))
)
(defclass Text (Element TMLElement)
    (content "")
    (updated ()
        false
    )
    (write (view redraw)
        (write view :content this)
    )
    (prefered-dims (dimensions)
        (dims (width dimensions) 1)
    )
    (constructor (str)
        (set :content this str)
        (set :name :header this "raw-text")
    )
)
(defclass div (TMLElement)
    (constructor (props children)
        (setl :children this children)
    )
)
(setl idf-regex (regex "\\w|@"))
(defun parse-idf (stream)
    (setl ret "")
    (while (not (eof stream))
        (if (matching idf-regex (peek-byte stream))
            (append ret (read-byte stream))
        else
            (break)
        )
    )
    ret
)


(setl extra-fields (dynamic (list)))
(defun parse-element (stream)
    #assumes that it start on the byte after <
    (setl ret (Element))
    (set :header ret (parse-header stream))
    (while (not (eof stream))
        (setl text-content (read-until stream "<"))
        (if (not (is-whitespace text-content))
            (append :children ret (Text (trim text-content)))
        )
        (if (eq (peek-byte stream) "/")
            (read-byte stream)
            (setl end-name (parse-idf stream))
            (skip-whitespace stream)
            (if (not (eq (peek-byte stream) ">"))
                (error "Close tag needs >")
            )
            (read-byte stream)
            (if (eq end-name :name :header ret)
                (break)
            )
        )
        (append :children ret (parse-element stream))
    )
    ret
)

(defun parse-header (stream)
    #assumes that it start on the byte after <
    (setl ret (Header))
    (set :name ret (parse-idf stream))
    (while (not (eof stream))
        (setl atr (Attribute))
        (skip-whitespace stream)
        (if (eq (peek-byte stream) "/")
            (read-byte stream)
            (if (not (eq (peek-byte stream) ">"))
                (error (+ "Invalid character after '/' in header: " (peek-byte stream)))
            )
            (read-byte stream)
            (break)
        )
        (if (eq (peek-byte stream) ">")
            (read-byte stream)
            (break)
        )
        (set :name atr (parse-idf stream))
        (if (eq (len :name atr) 0)
            (error (+ "Invalid attribute character: " (peek-byte stream)))
        )
        (if (eq (substr :name atr 0 1) "@")
            (setl :field-name ret (symbol (substr :name atr 1)))
            (if (not (eq :name atr "@input"))
                (append extra-fields :field-name ret)
            )
            (skip-whitespace stream)
            (continue)
        )
        (skip-whitespace stream)
        (if (eq (peek-byte stream) "=")
            (read-byte stream)
            #(setl :value atr (read-term stream))
            (skip-whitespace stream)
            (if (matching idf-regex (peek-byte stream))
                (setl :value atr (parse-idf stream))
             else 
                (if (eq (peek-byte stream) "@") (read-byte stream))
                (setl :value atr (read-term stream))
                (setl :is-parameter-value atr false)
            )
            (setl :mandatory atr false)
          else
            (setl :mandatory atr true)
        )
        (set ;:name atr :attributes ret atr)
    )
    ret
)
(defmethod str-mul (str count)
    (setl ret "")
    (dotimes count
        (append ret str)
    )
    ret
)
(defmethod str_impl ((el Element) depth)
    (setl padding (str-mul "    " depth))
    (setl ret (copy padding))
    (incr ret :name :header el)
    (doit key (keys :attributes :header el)
        (setl atr ;key :attributes :header el)
        (append ret " ")
        (append ret :name atr)
        (if (not (eq :value atr null))
            (append ret "=")
            (append  ret (str :value atr))
        )
    )
    (doit child :children el
        (append ret "\n")
        (append ret (str_impl child (+ depth 1)))
    )
    ret
)
(defmethod str ((el Element))
    (setl ret (str_impl el 0))
    ret
)
(defmacro embed-dynamic (sym &envir envir)
    (setl ret (lambda () 
        (index envir sym)))
    ret
)
(defmethod convert-child ((el Element))
    (setl ret null)
    (setl atrs :attributes :header el)
    (setl attributes-sym (gensym))
    (setl child-sym (gensym))
    (setl field-name :field-name :header el)
    `(progn 
        (setl ,attributes-sym 
            (make-dict ,@(map _(cond :is-parameter-value ;_ atrs `(,_ (index current-params ,_) ) `(,_ ,:value ;_ atrs )) (keys atrs)  )))
        (let (( (,(embed-dynamic child-list)) (list)))
            ,@(map convert-child :children el)
            (setl ,child-sym ,(get-dynamic child-list))
        )
        ,(if (eq (type el) Text)
            `(append ,(get-dynamic child-list) ,el)
          else
            `(append 
                ,(get-dynamic child-list) 
                ,(if (eq field-name null)
                    `(,(symbol :name :header el) ,attributes-sym ,child-sym  )
                  else
                    `(set (index this (quote ,field-name)) (,(symbol :name :header el) ,attributes-sym ,child-sym  ))
                 )
             )
        )
     )
)
(set child-list (dynamic (list )))
(defmethod convert-element ((el Element))
    (setl ret false)
    (setl atrs :attributes :header el)
    (setl extra-fields :extra-fields el)
    (setl class-def 
    `(defclass ,(symbol :name :header el) (,TMLElement)
        ,@(map _(list _ null) extra-fields)
        (constructor (params children)
            (setl current-params (copy params))
            (setl children (list))
            ,@(map (lambda (atr) 
                (if :mandatory ;atr atrs
                    `(if (not (in ,atr current-params ))
                        (error ,(+ "Missing mandatory attribute for " :name :header el " '" atr "'"))
                     )
                 else
                    `(if (not (in ,atr current-params ))
                        false
                        (set (index current-params ,atr) ,:value ;atr atrs)
                     )
                )
                ) (keys :attributes :header el))
            (let ((  (,(embed-dynamic child-list)) (list)))
              ,@(map convert-child :children el)
              (setl :children this ,(get-dynamic child-list))
            )
        )
    ))
)

(defun parse-tml (stream)
    (setl return-value null)
    (skip-whitespace stream)
    (if (not (eq (peek-byte stream) "<"))
        (error "TML must start with '<'")
    )
    (read-byte stream)
    (let ((extra-fields (list)))
        (setl return-value (parse-element stream))
        (setl :extra-fields return-value extra-fields)
    )
    (return return-value)
)
#(set stream (open "TestMarkup.tml" "r")) 
#(setl tml (parse-tml stream))
#(print (str tml)) 
#(setl converted (convert-element tml))
#(print converted)
#(print (expand converted))
#(eval converted)
#(print (TestClass (make-dict ("Height" 12)) (list)))
