(import text)
(import cli)
(import lsp lsp)
#Base for all lisp defined elements, 
#default working as a stacker


(defmacro embed-dynamic (sym &envir envir)
    (setl ret (lambda () 
        (index envir sym)))
    ret
)

(defclass ElementBase ()
    (parent (new-updated-info))

    (set-parent-info (new-parent)
        (set-parent-info :parent this new-parent)
    )
    (set-children (children)
        null
    )
    (clear-children ()
        null
    )
    (set-focus (value)
        null
    )
    (get-cursor-info ()
        (cursor-info)
    )
    (prefered-dims (dimensions)
        (dims 1 1)
    )
    (updated ()
        (updated :parent this)
    )
    (handle-input (input)
        true
    )
    (write (view redraw)
        null
    )
    (set-updated (is-updated)
        (set-updated :parent this is-updated)
    )
)

(setl current-interaction-stack (dynamic null))
(defmacro handle-base (this-expr input-expr)
    (setl res-sym (gensym))
    `(progn 
        (if (not (,eq (index ,this-expr (quote input)) null))
            (return (,handle-input (index ,this-expr (quote input)) ,input-expr))
         else if (&& (,not (,eq (index ,this-expr (quote interaction-stack)) null)) (> (len (index ,this-expr (quote interaction-stack))) 0))
            (let (( (,(embed-dynamic current-interaction-stack)) (index ,this-expr (quote interaction-stack)) ))
                (setl ,res-sym (,handle-input (,index (,back ,(get-dynamic current-interaction-stack)) 'element) ,input-expr) )
                (if (not ,res-sym)
                    (,pop ,this-expr)
                    (return true)
                )
                (return true)
            )
         else if (,eq ,input-expr "esc")
            (return false)
        )
     )
)

(defclass TMLElement (ElementBase)
    (attributes (dict))
    (children (list))
    (logical-children (list))
    (expr-children (list))
    (input null)
    (interaction-stack null)

    (children ()
        :logical-children this
    )

    (set-children (children)
        (setl :children this children)
        (map _(set-parent-info _ :parent this) :children this)
    )
    (clear-children (children)
        (setl :children this children)
        (map _(set-parent-info _ :parent this) :children this)
    )
    (add-child (child)
        (set-parent-info child :parent this)
        (append :children this child)
    )
    (constructor (children)
        (setl :children this children)
    )
    (handle-input (input)
        #(if (not (eq :input this null))
        #    (return (handle-input :input this input))
        #)
        (handle-base this input)
        true
    )
    (get-cursor-info ()
        (if (not (eq :input this null))
            (return (get-cursor-info :input this))
        )
        (cursor-info )
    )
    (prefered-dims (dimensions)
        (setl prefered-width (max (map _(width (prefered-dims _ dimensions)) :children this)))
        (if (eq (type prefered-width) null_t) (setl prefered-width (width dimensions)))
        (setl prefered-height (height dimensions))
        (if (> (len :children this) 0)
            (setl prefered-height (foldl (map _(height (prefered-dims _ dimensions)) :children this) plus))

        )
        (dims prefered-width prefered-height)
    )

    (write (view redraw)
        (set-updated this false)
        (setl view-dims (dims view))
        (setl height-offset 0)
        (setl current-offset (+ (len :children this) (minus 0 1)))
        (while (>= current-offset 0)
            (setl child ;current-offset :children this)
            (setl dimensions (prefered-dims child view-dims))
            (setl dimensions (dims (cond (< (width dimensions) 0) 1 (width dimensions) )  (cond (< (height dimensions) 0) 1 (height dimensions))  ))
            (if (|| redraw (updated child))
                (write child (sub-view view height-offset 0) redraw)
            )
            (incr height-offset (height dimensions))
            (incr current-offset (minus 0 1))
        )
    )

    (set-focus (focused)
        (if (eq (len :children this) 1)
            (set-focus :0 :children this focused)
        )
    )

    (update ()
        (doit child :expr-children this
            (update child)
        )
        (set-updated this true)
    )
)


(defclass interaction-element ()
    (element null)
    (pop-callback null)

    (constructor (elem)
        (setl :element this elem)
    )
    (constructor (elem callback)
        (setl :element this elem)
        (setl :pop-callback this callback)
    )
)

(defmethod push ((this TMLElement) sub-element)
    (if (not (eq current-interaction-stack null))
        (append current-interaction-stack (interaction-element sub-element))
     else
        (set :interaction-stack this (list))
        (append :interaction-stack this (interaction-element sub-element))
    )
)

(defmethod push ((this TMLElement) sub-element callback)
    (if (not (eq current-interaction-stack null))
        (append current-interaction-stack (interaction-element sub-element callback))
     else
        (set :interaction-stack this (list))
        (append :interaction-stack this (interaction-element sub-element callback))
    )
)

(defmethod pop ((this TMLElement))
    (if (&& (not (eq current-interaction-stack null)) (> (len current-interaction-stack) 0))
        (setl top (pop current-interaction-stack))
        (if (not (eq :pop-callback top null))
            (:pop-callback top)
        )
    )
)




(defclass Attribute ()
    (name "")
    (value null)
    (mandatory true)
    (omittable false)
    (is-parameter-value true)
)
(defclass Header ()
    (name 'null)
    (attributes (dict))
    (field-name null)
    (assignments (list))
    (closed false)
)

(defclass Element ()
    (header (Header))
    (children (list))
    (extra-fields (list))
)
#(defclass Text (Element TMLElement)
#    (content "")
#    (write (view redraw)
#        (write view :content this)
#    )
#    (prefered-dims (dimensions)
#        (dims (min (width dimensions) (len :content this)) 1)
#    )
#    (constructor (str)
#        (set :content this str)
#        (set :name :header this (symbol "raw-text"))
#    )


(defclass ChildrenPlaceholder (ElementBase Element)
    (constructor () 
        null
    )
)
(defclass ExprElement (ElementBase Element)
    (content "")
    (expr null)
    (write (view redraw)
        (write view :content this)
        (set-updated this false)
    )
    (prefered-dims (dimensions)
        (dims (min (width dimensions) (len :content this)) 1)
    )
    (update ()
        (set-value this (:expr this))
    )
    (set-value (new-value)
        (if (applicable str new-value)
            (set :content this (str new-value))
          else
            (set :content this (+ "#'" (str (name (type new-value)))))
        )
        (set-updated this true)
    )
    (constructor (expr)
        (set :expr this expr)
    )
)
(defclass CodeElement (ElementBase Element)
    (statements (list))
    (constructor (statements)
        (set :statements this statements)
    )
)


(defmethod set-expr-children (this (children list_t))
    null
)
(defmethod set-expr-children ((this TMLElement) (children list_t))
    (setl :expr-children this children)
)

(defclass div (TMLElement)
    (constructor (props children)
        (setl :children this children)
    )
)
#(setl idf-regex (regex "\\w|@"))
(setl idf-regex (regex "[a-z]|[A-Z]|_|@"))
(defun parse-idf-string (stream)
    (setl ret "")
    (while (not (eof stream))
        (if (matching idf-regex (peek-byte stream))
            (append ret (read-byte stream))
        else
            (break)
        )
    )
    ret
)

(setl header-string-regex (regex "\\w|@|-|\\?"))
(defun parse-header-string (stream)
    (setl ret "")
    (while (not (eof stream))
        (if (matching header-string-regex (peek-byte stream))
            (append ret (read-byte stream))
        else
            (break)
        )
    )
    ret
)

(defun parse-idf (stream)
    (make-sym (parse-idf-string stream))
)

(setl extra-fields (dynamic (list)))
(setl content-regex (regex "([^@<]|\\.)*"))
(defun parse-element (stream)
    #assumes that it start on the byte after <
    (setl ret (Element))
    (set :header ret (parse-header stream))
    (if :closed :header ret (return ret))
    (while (not (eof stream))
        #(setl text-content (read-until stream "<"))
        (setl text-content (read-regex stream content-regex))
        (if (not (is-whitespace text-content))
            (append :children ret (Text (trim text-content)))
        )
        (if (eq (peek-byte stream) "<")
            (read-byte stream)
            (if (eq (peek-byte stream) "/")
                (read-byte stream)
                (setl end-name (parse-idf stream))
                (skip-whitespace stream)
                (if (not (eq (peek-byte stream) ">"))
                    (error "Close tag needs >")
                )
                (signal (lsp:extra-ast end-name))
                (read-byte stream)
                (if (eq end-name :name :header ret)
                    (break)
                )
            )
            (append :children ret (parse-element stream))
          else (eq (peek-byte stream) "@")
            (read-byte stream)
            (if (eq (peek-byte stream) "(")
                (setl new-expr (read-term stream))
                (if (&& (eq (type new-expr) list_t) (eq (len new-expr) 1))
                    (setl new-expr :0 new-expr)
                )
                (append :children ret (ExprElement new-expr))
            else if (eq (peek-byte stream) "{")
                (read-byte stream)
                (setl statements (list))
                (while (&& (not (eof stream)) (not (eq (peek-byte stream) "}")))
                    (append statements (read-term stream))
                    (skip-whitespace stream)
                )
                (read-byte stream)
                (append :children ret (CodeElement statements))
                (setl testsetest 123)
            else
                (setl idf (parse-idf stream))
                (skip-whitespace stream)
                (if (eq (peek-byte stream) "=")
                    (read-byte stream)
                    (append extra-fields (list idf (read-term stream)))
                 else if (eq idf 'children)
                    (append :children ret (ChildrenPlaceholder))
                 else 
                    (error (+ "Invalid character after extra field declaration: " (peek-byte stream)))
                )
            )
        )
    )
    ret
)

(defun parse-header (stream)
    #assumes that it start on the byte after <
    (setl ret (Header))
    (set :name ret (parse-idf stream))
    (while (not (eof stream))
        (skip-whitespace stream)
        (setl atr (Attribute))
        (if (eq (peek-byte stream) "/")
            (read-byte stream)
            (if (not (eq (peek-byte stream) ">"))
                (error (+ "Invalid character after '/' in header: " (peek-byte stream)))
            )
            (read-byte stream)
            (setl :closed ret true)
            (break)
        )
        (if (eq (peek-byte stream) ">")
            (read-byte stream)
            (break)
        )
        (set :name atr (parse-header-string stream))
        (setl name-str :name atr)
        (setl token (make-sym name-str))
        (signal (lsp:semantic-token token "var"))
        (if (eq (len name-str) 0)
            (error (+ "Invalid attribute character: " (peek-byte stream)))
        )
        (if (eq (substr name-str 0 1) "@")
            #(setl :field-name ret (make-sym (substr name-str 1)))
            (setl field-name (make-sym (substr name-str 1)))
            (skip-whitespace stream)
            (if (eq (peek-byte stream) "=")
                (read-byte stream)
                (setl value (read-term stream))
                (append :assignments ret (list field-name value))
                (continue)
            )
            (setl :field-name ret field-name)
            (if (not (eq name-str "@input"))
                (append extra-fields (list :field-name ret null))
            )
            (continue)
        )
        (if (&& (> (len name-str) 0) (eq :-1 name-str "?"))
            (set :name atr (substr :name atr 0 (+ (len :name atr) -1)))
            (setl :omittable atr true)
            (setl :mandatory atr false)
        )

        (skip-whitespace stream)
        (if (eq (peek-byte stream) "=")
            (read-byte stream)
            #(setl :value atr (read-term stream))
            (skip-whitespace stream)
            (setl next-character (peek-byte stream))
            (if (&& (matching idf-regex next-character) (not (eq next-character "-")) (not (eq next-character "@")))
                (setl :value atr (parse-header-string stream))
                (if (eq :value atr "true")
                    (set :value atr true)
                    (setl :is-parameter-value atr false)
                else if (eq :value atr "false")
                    (set :value atr false)
                    (setl :is-parameter-value atr false)
                else 
                    (setl :value atr (symbol :value atr))
                )
             else 
                #(if (eq (peek-byte stream) "@") (read-byte stream))
                (setl :value atr (read-term stream))
                (setl :is-parameter-value atr false)
            )
            #(setl :value atr (read-term stream))
            #(setl :is-parameter-value atr false)
            (setl :mandatory atr false)
          else if (not :omittable atr)
            (setl :mandatory atr true)
        )
        (set ;:name atr :attributes ret atr)
    )
    ret
)
(defmethod str-mul (str count)
    (setl ret "")
    (dotimes count
        (append ret str)
    )
    ret
)
(defmethod str_impl ((el Element) depth)
    (setl padding (str-mul "    " depth))
    (setl ret (copy padding))
    (incr ret (str :name :header el))
    (doit key (keys :attributes :header el)
        (setl atr ;key :attributes :header el)
        (append ret " ")
        (append ret :name atr)
        (if (not (eq :value atr null))
            (append ret "=")
            (append  ret (str :value atr))
        )
    )
    (doit child :children el
        (append ret "\n")
        (append ret (str_impl child (+ depth 1)))
    )
    ret
)
(defmethod str ((el Element))
    (setl ret (str_impl el 0))
    ret
)
(defmethod convert-child ((el Text_t) emit)
    `(append ,(get-dynamic child-list) ,el)
)
#(setl ,attributes-sym 
#    (,make-dict ,@(map _(cond :is-parameter-value ;_ atrs `(,_ (index current-params ,_) ) `(,_ ,:value ;_ atrs )) (keys atrs)  )))
(defmethod convert-child ((el Element) (emit bool_t))
    (setl ret null)
    (setl atrs :attributes :header el)
    (setl attributes-sym (gensym))
    (setl child-sym (gensym))
    (setl value-sym (gensym))
    (setl dict-sym (gensym))
    (setl field-name :field-name :header el)
    `(progn 
        (setl ,attributes-sym 
            (progn 
                (setl ,dict-sym (dict)) 
                ,@(map _(cond :is-parameter-value ;_ atrs 
                    (if (eq :-1 (str :value ;_ atrs) "?")
                       (setl supplied-name (str :value ;_ atrs))
                       (setl real-name (substr supplied-name 0 (+ (len supplied-name) -1)))
                       `(if (in ,real-name current-params) 
                            (setl (index ,dict-sym ,real-name) (index current-params ,real-name))
                        )
                    else
                        `(setl (index ,dict-sym ,_) (index current-params ,(str :value ;_ atrs)))
                    )
                        `(setl (index ,dict-sym ,_) ,:value ;_ atrs )
                    )

                        (keys atrs)  

                  )
                  ,dict-sym
            )
        )
        (let (  ((,(embed-dynamic child-list)) (list)) )
            ,@(map _(convert-child _ emit) :children el )
            (setl ,child-sym ,(get-dynamic child-list))
        )
        ,(if (eq (type el) Text_t)
            `(append ,(get-dynamic child-list) ,el)
           else if (eq (type el) ExprElement)
             (setl expr-sym (gensym))
             `(progn 
                (setl ,expr-sym (,ExprElement (lambda () ,:expr el)))
                (append ,(get-dynamic child-list) ,expr-sym)
                (append ,(get-dynamic expr-child-list) ,expr-sym)
              )
           else if (eq (type el) ChildrenPlaceholder)
             `(insert-elements ,(get-dynamic child-list) children)
           else if (eq (type el) CodeElement)
             `(progn ,@:statements el)
          else
            `(progn 
               (setl ,value-sym 
                    ,(if (eq field-name null)
                        `(,:name :header el ,attributes-sym ,child-sym  )
                      else
                        `(progn 
                            ,(cond emit
                                `(setl ,field-name (,:name :header el ,attributes-sym ,child-sym  ))
                                `(setl (index this (quote ,field-name)) (,:name :header el ,attributes-sym ,child-sym  ))
                             )
                         )
                     ))
                ,@(map _(progn `(set (index ,value-sym (quote ,:0 _))  ,:1 _  )) :assignments :header el)

                 (append 
                    ,(get-dynamic child-list) 
                    ,value-sym
                 )
             )
        )
     )
)
(set child-list (dynamic (list )))
(set expr-child-list (dynamic (list )))


(defmethod emit-child (child)
    (append child-list child)
)


(defmethod convert-element ((el Element))
    (setl ret false)
    (setl atrs :attributes :header el)
    (setl fields (copy :extra-fields el))
    #(setl class-def 
    (insert-elements fields (map _(list (symbol _) null) (keys :attributes :header el)))

    (setl child-forms (map (lambda (atr) 
                (setl param-symbol (symbol atr))
                (if :mandatory ;atr atrs
                    `(progn 
                         (if (not (in ,atr current-params ))
                            (error ,(+ "Missing mandatory attribute for " (str :name :header el) " '" atr "'"))
                         )
                         (setl ,param-symbol (index current-params ,atr))
                     )
                 else
                    (setl value-sym (gensym))
                    `(if (not (in ,atr current-params ))
                        (setl ,value-sym ,:value ;atr atrs)
                        ,(if (not :omittable ;atr atrs) `(set (index current-params ,atr) ,value-sym) )
                        (setl ,param-symbol ,value-sym)
                        (setl (index this (quote ,param-symbol) ) ,value-sym)
                     else
                        (setl ,param-symbol (index current-params ,atr))
                        (setl (index this (quote ,param-symbol) ) (index current-params ,atr))
                     )
                )
                ) (keys :attributes :header el)))

    (append child-forms 
            `(let ((  (,(embed-dynamic child-list)) (list))  ((,(embed-dynamic expr-child-list)) (list)))
              ,@(map _(convert-child _ false) :children el )
              (,set-children this ,(get-dynamic child-list))
              (,set-expr-children this ,(get-dynamic expr-child-list))
            ))

    (setl field-assignments (map 
                _(progn `(set (index this (quote ,:0 _)) ,:1 _)) 
                (filter _(not (eq null :1 _)) fields))
            )
    `(defclass ,:name :header el (,TMLElement)
        ,@(map _(list :0 _ null) fields)
        (constructor ()
            (setl current-params (dict))
            (setl children (list))
            ,@child-forms
            ,@field-assignments
            (set :logical-children this children)
            (update this)
        )
        (constructor (params children)
            (setl current-params (copy params))
            #(setl children (list))
            ,@child-forms
            ,@field-assignments
            (set :logical-children this children)
            (update this)
        )
    )
)

(defun parse-tml (stream)
    (setl return-value null)
    (skip-whitespace stream)
    (if (not (eq (peek-byte stream) "<"))
        (error "TML must start with '<'")
    )
    (read-byte stream)
    (let ((extra-fields (list)))
        (setl return-value (parse-element stream))
        (setl :extra-fields return-value extra-fields)
    )
    (return return-value)
)
(defun tml (stream)
    (convert-element (parse-tml stream))
)
(defun tml-emit (stream)
    (setl parse-res (parse-tml stream))
    (setl res-sym (gensym))
    (setl it-sym (gensym))
    (setl child-forms 
            `(let ((  (,(embed-dynamic child-list)) (list))  ((,(embed-dynamic expr-child-list)) (list)))
              (setl ,res-sym null)
              ,(convert-child parse-res true)
              (setl ,res-sym  (index  ,(get-dynamic child-list) 0))
              (doit ,it-sym ,(get-dynamic expr-child-list)
                (,update ,it-sym)
              )
              ,res-sym
            ))
    child-forms
)

(defun display-window (window)
    (setl term (terminal))
    (clear term)
    (write-window term window)
    (while true
        (setl new-input (get-input term))
        (handle-input window new-input)
        (write-window term window)
    )
)

