(import tml)
#(import tml tml-scope)

#(setl argv (list "TestMarkup.tml"))
(if (< (len argv) 1) (error "TMLDisplay needs path name as the first argument"))
(setl file :0 argv)
#(set stream (open file "r")) 
#(setl tml (parse-tml stream))
#(setl converted (convert-element tml))
(setl new-scope (new-environment))
#(set-parent new-scope tml-scope)
#(eval converted new-scope)
(eval `(load ,file) new-scope)

(doit key (vars new-scope)
    (setl current-value ;key new-scope)
    (if (&& (eq (type current-value) type_t) (is current-value TMLElement))
        (setl term (terminal))
        (clear term)
        (setl window (current-value (dict) (list)))
        (write-window term window)
        (while true
            (setl new-input (get-input term))
            (handle-input window new-input)
            (write-window term window)
        )
    )
)
(error (+ "No TML element defined in file: " file))
